apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: leos-pizza-hpa
  namespace: pizza  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leos-pizza-deployment  
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50  
