# Generated by Django 4.2.16 on 2024-09-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_type',
            field=models.CharField(choices=[('Margherita', 'Margherita'), ('Pepperoni', 'Pepperoni'), ('Vegetarian', 'Vegetarian'), ('Hawaiian', 'Hawaiian'), ('BBQ Chicken', 'BBQ Chicken'), ('Four Cheese', 'Four Cheese'), ('Mushroom', 'Mushroom'), ('Mexicana', 'Mexicana')], max_length=50),
        ),
    ]
